\connect simulation;

-- Tables

CREATE TABLE distances (
  origin TEXT PRIMARY KEY,
  KATL DOUBLE PRECISION,
  KDFW DOUBLE PRECISION,
  KDEN DOUBLE PRECISION,
  KORD DOUBLE PRECISION,
  KLAX DOUBLE PRECISION,
  KJFK DOUBLE PRECISION,
  KCLT DOUBLE PRECISION,
  KLAS DOUBLE PRECISION,
  KMCO DOUBLE PRECISION,
  KMIA DOUBLE PRECISION,
  KPHX DOUBLE PRECISION,
  KSEA DOUBLE PRECISION,
  KSFO DOUBLE PRECISION,
  KEWR DOUBLE PRECISION,
  KIAH DOUBLE PRECISION,
  KBOS DOUBLE PRECISION,
  KMSP DOUBLE PRECISION,
  KFLL DOUBLE PRECISION,
  KLGA DOUBLE PRECISION,
  KDTW DOUBLE PRECISION,
  KPHL DOUBLE PRECISION,
  KSLC DOUBLE PRECISION,
  KBWI DOUBLE PRECISION,
  KIAD DOUBLE PRECISION,
  KSAN DOUBLE PRECISION,
  KDCA DOUBLE PRECISION,
  KTPA DOUBLE PRECISION,
  KBNA DOUBLE PRECISION,
  KAUS DOUBLE PRECISION,
  PHNL DOUBLE PRECISION,
  LFPG DOUBLE PRECISION
);

CREATE TABLE travelers (
  origin TEXT PRIMARY KEY,
  KATL INTEGER,
  KDFW INTEGER,
  KDEN INTEGER,
  KORD INTEGER,
  KLAX INTEGER,
  KJFK INTEGER,
  KCLT INTEGER,
  KLAS INTEGER,
  KMCO INTEGER,
  KMIA INTEGER,
  KPHX INTEGER,
  KSEA INTEGER,
  KSFO INTEGER,
  KEWR INTEGER,
  KIAH INTEGER,
  KBOS INTEGER,
  KMSP INTEGER,
  KFLL INTEGER,
  KLGA INTEGER,
  KDTW INTEGER,
  KPHL INTEGER,
  KSLC INTEGER,
  KBWI INTEGER,
  KIAD INTEGER,
  KSAN INTEGER,
  KDCA INTEGER,
  KTPA INTEGER,
  KBNA INTEGER,
  KAUS INTEGER,
  PHNL INTEGER,
  LFPG INTEGER
);

-- Load CSVs 

COPY distances FROM '/docker-entrypoint-initdb.d/distances.csv'
WITH (FORMAT csv, HEADER true);

COPY travelers FROM '/docker-entrypoint-initdb.d/travelers.csv'
WITH (FORMAT csv, HEADER true);